# ci-cd/.github/workflows/ci-cd.yml
name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to Docker Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./docker
          push: true
          tags: your-registry.example.com/obp-api:${{ github.sha }}
          build-args: |
            OBP_VERSION=4.0.0

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          
      - name: Install dependencies
        run: |
          cd tests
          pip install -r requirements.txt
          
      - name: Run tests
        run: |
          cd tests
          python -m pytest api_tests.py -v

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        
      - name: Set up Kubernetes config
        run: echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig
        
      - name: Update manifests
        run: |
          cd k8s
          sed -i "s/\${REGISTRY}/your-registry.example.com/g" obp-api.yaml
          sed -i "s/\${TAG}/${{ github.sha }}/g" obp-api.yaml
          
      - name: Deploy to Kubernetes
        run: |
          export KUBECONFIG=./kubeconfig
          export ENVIRONMENT=$(echo ${{ github.ref }} | sed -e "s/refs\/heads\///g")
          kubectl create namespace obp-${ENVIRONMENT} --dry-run=client -o yaml | kubectl apply -f -
          kubectl apply -f k8s/storage.yaml -n obp-${ENVIRONMENT}
          kubectl create secret generic obp-db-credentials --from-literal=username=obp --from-literal=password=obpsecurepassword -n obp-${ENVIRONMENT} --dry-run=client -o yaml | kubectl apply -f -
          kubectl apply -f k8s/database.yaml -n obp-${ENVIRONMENT}
          kubectl apply -f k8s/obp-api.yaml -n obp-${ENVIRONMENT}
          kubectl apply -f k8s/ingress.yaml -n obp-${ENVIRONMENT}